### ISSUE TITLE
Class li3_doctrine\\extensions\\data\\source\\Doctrine contains 1 abstract method ...

### ISSUE THREAD

**Issue by ghost** [mackstar/li3_doctrine#1]
PHP Fatal error:  Class li3_doctrine\extensions\data\source\Doctrine contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (lithium\data\Source::sources) in /public_html/framework/app/libraries/li3_doctrine/extensions/data/source/Doctrine.php on line 28

**Comment by mackstar** [comment]
Hi thanks for the feedback,

I will fix this in the next few days.

Cheers

Richard

**Comment by ghost** [comment]
np, was just happy to maybe have found a plugin that can connect to my firebird database directly.
